version: '3.8'
services:
  back:
    build: ./margulan-back
    container_name: back-container
    ports: 
      - '3001:3001'
    volumes:
      - /Users/defida/Documents/Margulan/margulan-back:/back-container
      - /back-container/node_modules
  front:
    stdin_open: true
    build: ./margulan
    container_name: front-container
    ports:
      - "3000:3000"
    tty: true